apiVersion: milkman/alphav1
kind: Script
metadata:
  name: check hello
spec:
  dependsOn: ["say hello"]
  script: |
    console.log("check request");
    test(context.get("status") == 200, "status should be 200");
    console.log("tested");
    context.set("message", context.get("response").data.message);